name: kawa-market
region: nyc

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

features:
  - buildpack-stack=ubuntu-22

databases:
  - engine: PG
    name: dev-db
    version: "17"

# Static site for the Vue frontend
static_sites:
  - name: kawa-web
    github:
      branch: main
      deploy_on_push: true
      repo: keenan-v1/kawa.wantsmore.coffee
    source_dir: /
    build_command: npm install -g pnpm && pnpm install && pnpm --filter @kawakawa/types build && pnpm --filter @kawakawa/web build
    output_dir: apps/web/dist
    environment_slug: node-js
    routes:
      - path: /

# API service
services:
  - name: kawa-api
    github:
      branch: main
      deploy_on_push: true
      repo: keenan-v1/kawa.wantsmore.coffee
    source_dir: /
    build_command: npm install -g pnpm && pnpm install && pnpm --filter @kawakawa/types build && pnpm --filter @kawakawa/api build
    run_command: node apps/api/dist/index.js
    environment_slug: node-js
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${dev-db.DATABASE_URL}
      - key: PORT
        scope: RUN_TIME
        value: "3000"
    routes:
      - path: /api
